### ISSUE TITLE
PyiCloudNoStoredPasswordAvailableException occurs when trying to get a login session

### ISSUE THREAD

**Issue by itavero** [chrisns/icloud-photos-backup#295]
Tried following the commands from the `README.md`, but when issuing the second command (_Get or renew a login session with 2FA_), I get the following error after entering my password:

```
docker run \
  -u $USERID \
  --rm -ti \
  -v ${PWD}/session:/tmp/pyicloud \
  -v ${PWD}/keyring:/home/app/.local/share/python_keyring \
  -e USERNAME="my@emailadr.es" \
  ghcr.io/chrisns/icloud-photos-backup
iCloud Password: 
Traceback (most recent call last):
  File "/app/backup.py", line 137, in authenticate
    api = PyiCloudService(username)
  File "/usr/local/lib/python3.10/site-packages/pyicloud/base.py", line 217, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/local/lib/python3.10/site-packages/pyicloud/utils.py", line 41, in get_password_from_keyring
    raise PyiCloudNoStoredPasswordAvailableException(
pyicloud.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for my@emailadr.es could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backup.py", line 186, in <module>
    backup()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/backup.py", line 56, in backup
    icloud = authenticate(username)
  File "/app/backup.py", line 141, in authenticate
    store_password_in_keyring(username, password)
  File "/usr/local/lib/python3.10/site-packages/pyicloud/utils.py", line 55, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/local/lib/python3.10/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/usr/local/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 129, in set_password
    self._write_config_value(service, username, password_base64)
  File "/usr/local/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 137, in _write_config_value
    self._ensure_file_path()
  File "/usr/local/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 163, in _ensure_file_path
    os.makedirs(storage_root)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
```

Any clue how to solve this?

Note that I am running macOS 12.6 Monterey and I have run the earlier `chown` command using `sudo`.

**Comment by itavero** [comment]
Leaving out `--u $USERID` from the Docker commands does seem to resolve this issue for me.
